---

- name: Create installation directory
  file:
    state: directory
    path: "{{ sap.install_dir|default('/srv/sap/bo') }}"
    owner: "{{ system_user|default('hmpps_sys_user') }}"
    mode: 0755
  become: true

- name: Create installer directory
  file:
    state: directory
    path: "{{ sap.installer_dir|default('/srv/sap/installers') }}"
    owner: "{{ system_user|default('hmpps_sys_user') }}"
    mode: 0755
  become: true