---

- name: Unpack our archives
  command: "unrar x -y {{ item.dest_path }}/{{ item.name }}"
  args:
    chdir: "{{ item.dest_path }}"
  with_items: "{{ sap_artefacts }}"
  become: true
  become_user: "{{ default_sys_user }}"
#
#- name: Remove our unpacked archive
#  file:
#    path: "{{ item.dest_path }}/{{ item.name }}"
#    state: absent
#  with_items: "{{ sap_artefacts }}"
#  become: true
#  become_user: "{{ default_sys_user }}"

- name: Copy our response file to our temp dir
  template:
    src: "{{ role_path }}/templates/sap_bo.rsp.j2"
    dest: "/tmp/sap_bo.rsp"
