---

- name: Unpack our archives
  command: "unrar x -y {{ item.dest_path }}/{{ item.name }}"
  args:
    chdir: "{{ item.dest_path }}"
  with_items: "{{ sap_artefacts }}"
  when: item.name.lower().find('.rar') > 0
  become: true
  become_user: "{{ default_sys_user }}"

- name: Remove our unpacked archive
  file:
    path: "{{ item.dest_path }}/{{ item.name }}"
    state: absent
  with_items: "{{ sap_artefacts }}"
  become: true
  become_user: "{{ default_sys_user }}"

- name: Unpack our BIPLATFORM.tgz file
  unarchive:
    src: "{{ sap.installer_dir }}/BIPLATFORM.tgz"
    dest: "{{ sap.installer_dir }}/biplatform"
    remote_src: true
  become: true
  become_user: "{{ default_sys_user }}"

- name: Remove our BIPLATFORM.tgz file
  file:
    path: "{{ sap.installer_dir }}/BIPLATFORM.tgz"
    state: absent
  become: true
  become_user: "{{ default_sys_user }}"

- name: Retrieve our product key from ssm
  set_fact:
    sap_product_key: "{{ lookup('aws_ssm', product_key|trim(), decrypt=True, region='eu-west-2' ) }}"

- name: Copy our response file to our temp dir
  template:
    src: "{{ role_path }}/templates/sap_bo.rsp.j2"
    dest: "/tmp/sap_bo.rsp"

- name: Install SAP
  command: ./setup.sh -r /tmp/sap_bo.rsp
  args:
    chdir: /srv/sap/installers/51052102/DATA_UNITS/BusinessObjectsServer_lnx
  become: true
  become_user: hmpps_sys_user

#- name: Remove our installer
#  file:
#    path: /srv/sap/installers/51052102
#    state: absent
#  become: true
