---

#- name: Unpack our archives and remove the rar file once done
#  command: "unrar x {{ item.dest_path }}/{{ item.name }}; \
#            chown -R {{ default_sys_user }}:{{ default_sys_user }} {{ item.dest_path }}/{{ item.name }}; \
#            rm -rf {{ item.dest_path }}/{{ item.name }}"
#  with_items: "{{ sap_artefacts }}"
#  become: true
