---

- name: Turn off our ulimits
  pam_limits:
    limit_type: "{{ system.limit_type|default('-') }}"
    limit_item: "{{ item.name }}"
    value: "{{ item.value|default('unlimited') }}"
    domain: "{{ system.system_user|default('hmpps_sys_user') }}"
  with_items: "{{ system.ulimits|default([{name:'stack'}]) }}"
  become: true

- block:
  - name: Set some specific limits
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
    with_items: "{{ system.sysctl }}"
    become: true
  when: "{{ system.sysctl| default(false) }}"
